export const surpriseMePrompts = [
  'a sleek red sports car racing on the rings of Saturn, digital art',
  'a Lamborghini drifting on the moon with Earth in the background, hyper-realistic',
  'a Formula 1 car launching into space from a neon-lit runway, cyberpunk style',
  'an astronaut fixing a floating Bugatti in zero gravity, digital painting',
  'a futuristic Tesla Roadster hovering above a Martian canyon, photorealistic',
  'a car showroom inside a space station orbiting Jupiter, ultra-modern interior',
  'a spaceship designed like a McLaren, blazing through a meteor field',
  'a concept sports car flying through a wormhole, vaporwave colors',
  'an alien test-driving a Ferrari on the surface of Pluto, comic style',
  'a drifting sports car leaving behind trails of stardust, digital art',
  'a space mechanic tuning a Corvette with robotic arms, in a zero-g garage',
  'a neon-lit street race between starships and sports cars on an asteroid belt',
  'a holographic dashboard in a flying Porsche inside a luxury space shuttle',
  'a futuristic tunnel filled with speeding space cars, Blade Runner style',
  'a matte black sports car parked on a moon crater under a starry sky',
  'a drifting DeLorean time machine in a cosmic nebula, 80s retro style',
  'a cyberpunk police interceptor chasing a rogue sports car on a space highway',
  'an astronaut valet parking a gold-plated hypercar outside a Mars hotel',
  'a car engine powered by a glowing alien crystal, sci-fi concept sketch',
  'a spaceship pit stop designed like a luxury auto garage, digital concept art',
  'a spacecraft shaped like a Formula E car launching from a hangar',
  'a space drag race between levitating supercars over a black hole horizon',
  'a convertible flying through asteroid traffic with rocket boosters engaged',
  'a group of astronauts admiring a Bugatti on Europa’s icy surface',
  'a self-driving space coupe navigating Saturn’s storm clouds, digital painting',
  'a vintage muscle car with anti-gravity thrusters floating near a space station',
  'a cosmic car commercial shot in zero gravity with dramatic lighting',
  'a luxury space limousine passing by the International Space Station, 3D render',
  'a cyber-race arena with glowing space cars and massive crowds in the stands',
  'an intergalactic Uber driver picking up aliens in a glowing sports car',
  'a robotic valet AI detailing a Ferrari in a Martian hangar bay',
  'a street race on a terraformed Venus with futuristic road cars',
  'a gravity-defying loop track in deep space with high-speed cars',
  'a cockpit view of a hypercar flying through the Andromeda galaxy',
  'an electric space sports bike overtaking a hovercar on a plasma highway',
  'a transparent glass sports car hovering over a solar flare, concept art',
  'a racing pit crew of robots preparing a space car for launch',
  'a spy in a stealth sports car escaping through a wormhole',
  'a rocket-propelled sports car breaking light speed in deep cosmos',
  'a luxury interplanetary car ad with chrome-finished space coupes',
  'a space parking garage stacked with custom alien hypercars',
  'a chrome sports car reflecting stars as it glides through space',
  'a modified Audi Quattro rallying on Mars, red dunes, photography',
  'a racing drone camera following a space car on a gravity-defying track',
  'a space car stunt show over the rings of Uranus, 3D animation',
  'a solar-powered sports car cruising through a galactic sunset',
  'a sci-fi concept of a car with retractable wings flying above Titan',
  'a sports car chase scene through a crashed alien spaceship, concept art'
];
